import { useState, FormEvent } from 'react';
import { PageHeader } from '@/components/ui/PageComponents';
import { CrudTable, Modal, Field, TextInput, SelectInput, FormActions, StatusBadge } from '@/components/ui/CrudComponents';
import { useCollection, useData } from '@/context/DataContext';
import { Report, Status } from '@/types/entities';
import { formatDateShort } from '@/lib/storage';

const emptyReport = (): Omit<Report, 'id' | 'createdAt' | 'updatedAt'> => ({
  name: '', type: 'Security', generatedBy: 'Super Admin', status: 'Completed', period: '',
});

export function SystemReports() {
  const { items, create, update, remove } = useCollection('reports');
  const { logActivity, showToast } = useData();
  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState<Report | null>(null);
  const [form, setForm] = useState(emptyReport());

  const openCreate = () => { setEditing(null); setForm(emptyReport()); setModalOpen(true); };
  const openEdit = (i: number) => {
    const r = items[i] as Report;
    setEditing(r);
    setForm({ name: r.name, type: r.type, generatedBy: r.generatedBy, status: r.status, period: r.period ?? '' });
    setModalOpen(true);
  };

  const handleDelete = (i: number) => {
    const r = items[i] as Report;
    if (confirm(`Delete report "${r.name}"?`)) {
      remove(r.id);
      logActivity(`Deleted report: ${r.name}`, 'System Reports');
      showToast('Report deleted');
    }
  };

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (editing) {
      update(editing.id, form);
      showToast('Report updated successfully');
    } else {
      create(form);
      logActivity(`Generated report: ${form.name}`, 'System Reports');
      showToast('Report saved successfully');
    }
    setModalOpen(false);
  };

  return (
    <div className="page-container">
      <PageHeader
        title="System-Wide Reports"
        description="Generate and manage reports stored in the system."
        actions={<button type="button" className="btn-primary" onClick={openCreate}>Generate Report</button>}
      />
      <CrudTable
        headers={['Report Name', 'Type', 'Generated By', 'Date', 'Status']}
        rows={(items as Report[]).map((r) => [r.name, r.type, r.generatedBy, formatDateShort(r.createdAt), <StatusBadge key={r.id} status={r.status} />])}
        onEdit={openEdit}
        onDelete={handleDelete}
      />
      <Modal open={modalOpen} title={editing ? 'Edit Report' : 'Generate Report'} onClose={() => setModalOpen(false)}>
        <form onSubmit={handleSubmit}>
          <div className="space-y-4">
            <Field label="Report Name"><TextInput required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field>
            <Field label="Type"><TextInput value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} /></Field>
            <Field label="Period"><TextInput value={form.period} onChange={(e) => setForm({ ...form, period: e.target.value })} /></Field>
            <Field label="Status">
              <SelectInput value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as Status })}>
                {['Completed', 'Pending', 'Draft'].map((s) => <option key={s} value={s}>{s}</option>)}
              </SelectInput>
            </Field>
          </div>
          <FormActions onCancel={() => setModalOpen(false)} submitLabel="Save Report" />
        </form>
      </Modal>
    </div>
  );
}
